# Production stage
FROM nginx:alpine AS production
COPY --from=builder /app/dist /usr/share/nginx/html
COPY /docker/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 6666
CMD ["nginx", "-g", "daemon off;"]
